"""add review count to lesson progress

Revision ID: b883e40f21a4
Revises: 3b775a3d3c07
Create Date: 2026-10-02 18:39:09.524882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b883e40f21a4'
down_revision: Union[str, Sequence[str], None] = '3b775a3d3c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_progress', sa.Column('review_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_progress', 'review_count')
    # ### end Alembic commands ###
